# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calculadora_trapecios.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDialog,
    QDialogButtonBox, QLabel, QLineEdit, QSizePolicy,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(845, 486)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(670, 450, 161, 32))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.comboBox = QComboBox(Dialog)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(20, 40, 103, 32))
        self.comboBox_2 = QComboBox(Dialog)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(120, 40, 103, 32))
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 58, 16))
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 20, 58, 16))
        self.lineEdit = QLineEdit(Dialog)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(60, 160, 51, 21))
        self.lineEdit_2 = QLineEdit(Dialog)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(60, 190, 51, 21))
        self.lineEdit_3 = QLineEdit(Dialog)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(60, 220, 51, 21))
        self.lineEdit_4 = QLineEdit(Dialog)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(60, 250, 51, 21))
        self.lineEdit_6 = QLineEdit(Dialog)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(60, 310, 51, 21))
        self.lineEdit_7 = QLineEdit(Dialog)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(60, 340, 51, 21))
        self.lineEdit_8 = QLineEdit(Dialog)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(60, 280, 51, 21))
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 160, 31, 16))
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 190, 31, 16))
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 220, 31, 16))
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 250, 31, 16))
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 340, 31, 16))
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 280, 31, 16))
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 310, 31, 16))
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 90, 58, 16))
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 130, 21, 16))
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(60, 130, 58, 16))
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 130, 58, 16))
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(200, 130, 58, 16))
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(270, 130, 58, 16))
        self.lineEdit_5 = QLineEdit(Dialog)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(130, 190, 51, 21))
        self.lineEdit_9 = QLineEdit(Dialog)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(130, 340, 51, 21))
        self.lineEdit_10 = QLineEdit(Dialog)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(130, 160, 51, 21))
        self.lineEdit_11 = QLineEdit(Dialog)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(130, 220, 51, 21))
        self.lineEdit_12 = QLineEdit(Dialog)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(130, 250, 51, 21))
        self.lineEdit_13 = QLineEdit(Dialog)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(130, 280, 51, 21))
        self.lineEdit_14 = QLineEdit(Dialog)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(130, 310, 51, 21))
        self.lineEdit_15 = QLineEdit(Dialog)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(200, 190, 51, 21))
        self.lineEdit_16 = QLineEdit(Dialog)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(200, 340, 51, 21))
        self.lineEdit_17 = QLineEdit(Dialog)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(200, 160, 51, 21))
        self.lineEdit_18 = QLineEdit(Dialog)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(200, 220, 51, 21))
        self.lineEdit_19 = QLineEdit(Dialog)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(200, 250, 51, 21))
        self.lineEdit_20 = QLineEdit(Dialog)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(200, 280, 51, 21))
        self.lineEdit_21 = QLineEdit(Dialog)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(200, 310, 51, 21))
        self.lineEdit_22 = QLineEdit(Dialog)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(340, 280, 51, 21))
        self.lineEdit_23 = QLineEdit(Dialog)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(410, 340, 51, 21))
        self.lineEdit_24 = QLineEdit(Dialog)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(270, 190, 51, 21))
        self.lineEdit_25 = QLineEdit(Dialog)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(410, 220, 51, 21))
        self.lineEdit_26 = QLineEdit(Dialog)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.lineEdit_26.setGeometry(QRect(410, 310, 51, 21))
        self.lineEdit_27 = QLineEdit(Dialog)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(410, 160, 51, 21))
        self.lineEdit_28 = QLineEdit(Dialog)
        self.lineEdit_28.setObjectName(u"lineEdit_28")
        self.lineEdit_28.setGeometry(QRect(340, 310, 51, 21))
        self.lineEdit_29 = QLineEdit(Dialog)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(270, 340, 51, 21))
        self.lineEdit_30 = QLineEdit(Dialog)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(270, 160, 51, 21))
        self.lineEdit_31 = QLineEdit(Dialog)
        self.lineEdit_31.setObjectName(u"lineEdit_31")
        self.lineEdit_31.setGeometry(QRect(340, 250, 51, 21))
        self.lineEdit_32 = QLineEdit(Dialog)
        self.lineEdit_32.setObjectName(u"lineEdit_32")
        self.lineEdit_32.setGeometry(QRect(270, 220, 51, 21))
        self.lineEdit_33 = QLineEdit(Dialog)
        self.lineEdit_33.setObjectName(u"lineEdit_33")
        self.lineEdit_33.setGeometry(QRect(410, 250, 51, 21))
        self.lineEdit_34 = QLineEdit(Dialog)
        self.lineEdit_34.setObjectName(u"lineEdit_34")
        self.lineEdit_34.setGeometry(QRect(270, 250, 51, 21))
        self.lineEdit_35 = QLineEdit(Dialog)
        self.lineEdit_35.setObjectName(u"lineEdit_35")
        self.lineEdit_35.setGeometry(QRect(340, 220, 51, 21))
        self.lineEdit_36 = QLineEdit(Dialog)
        self.lineEdit_36.setObjectName(u"lineEdit_36")
        self.lineEdit_36.setGeometry(QRect(270, 280, 51, 21))
        self.lineEdit_37 = QLineEdit(Dialog)
        self.lineEdit_37.setObjectName(u"lineEdit_37")
        self.lineEdit_37.setGeometry(QRect(410, 280, 51, 21))
        self.lineEdit_38 = QLineEdit(Dialog)
        self.lineEdit_38.setObjectName(u"lineEdit_38")
        self.lineEdit_38.setGeometry(QRect(410, 190, 51, 21))
        self.lineEdit_39 = QLineEdit(Dialog)
        self.lineEdit_39.setObjectName(u"lineEdit_39")
        self.lineEdit_39.setGeometry(QRect(340, 190, 51, 21))
        self.lineEdit_40 = QLineEdit(Dialog)
        self.lineEdit_40.setObjectName(u"lineEdit_40")
        self.lineEdit_40.setGeometry(QRect(270, 310, 51, 21))
        self.lineEdit_41 = QLineEdit(Dialog)
        self.lineEdit_41.setObjectName(u"lineEdit_41")
        self.lineEdit_41.setGeometry(QRect(340, 160, 51, 21))
        self.lineEdit_42 = QLineEdit(Dialog)
        self.lineEdit_42.setObjectName(u"lineEdit_42")
        self.lineEdit_42.setGeometry(QRect(340, 340, 51, 21))
        self.lineEdit_43 = QLineEdit(Dialog)
        self.lineEdit_43.setObjectName(u"lineEdit_43")
        self.lineEdit_43.setGeometry(QRect(480, 190, 51, 21))
        self.lineEdit_44 = QLineEdit(Dialog)
        self.lineEdit_44.setObjectName(u"lineEdit_44")
        self.lineEdit_44.setGeometry(QRect(480, 310, 51, 21))
        self.lineEdit_45 = QLineEdit(Dialog)
        self.lineEdit_45.setObjectName(u"lineEdit_45")
        self.lineEdit_45.setGeometry(QRect(480, 160, 51, 21))
        self.lineEdit_46 = QLineEdit(Dialog)
        self.lineEdit_46.setObjectName(u"lineEdit_46")
        self.lineEdit_46.setGeometry(QRect(480, 340, 51, 21))
        self.lineEdit_47 = QLineEdit(Dialog)
        self.lineEdit_47.setObjectName(u"lineEdit_47")
        self.lineEdit_47.setGeometry(QRect(480, 220, 51, 21))
        self.lineEdit_48 = QLineEdit(Dialog)
        self.lineEdit_48.setObjectName(u"lineEdit_48")
        self.lineEdit_48.setGeometry(QRect(480, 250, 51, 21))
        self.lineEdit_49 = QLineEdit(Dialog)
        self.lineEdit_49.setObjectName(u"lineEdit_49")
        self.lineEdit_49.setGeometry(QRect(480, 280, 51, 21))
        self.lineEdit_50 = QLineEdit(Dialog)
        self.lineEdit_50.setObjectName(u"lineEdit_50")
        self.lineEdit_50.setGeometry(QRect(550, 190, 51, 21))
        self.lineEdit_51 = QLineEdit(Dialog)
        self.lineEdit_51.setObjectName(u"lineEdit_51")
        self.lineEdit_51.setGeometry(QRect(550, 340, 51, 21))
        self.lineEdit_52 = QLineEdit(Dialog)
        self.lineEdit_52.setObjectName(u"lineEdit_52")
        self.lineEdit_52.setGeometry(QRect(550, 280, 51, 21))
        self.lineEdit_53 = QLineEdit(Dialog)
        self.lineEdit_53.setObjectName(u"lineEdit_53")
        self.lineEdit_53.setGeometry(QRect(550, 250, 51, 21))
        self.lineEdit_54 = QLineEdit(Dialog)
        self.lineEdit_54.setObjectName(u"lineEdit_54")
        self.lineEdit_54.setGeometry(QRect(550, 160, 51, 21))
        self.lineEdit_55 = QLineEdit(Dialog)
        self.lineEdit_55.setObjectName(u"lineEdit_55")
        self.lineEdit_55.setGeometry(QRect(550, 310, 51, 21))
        self.lineEdit_56 = QLineEdit(Dialog)
        self.lineEdit_56.setObjectName(u"lineEdit_56")
        self.lineEdit_56.setGeometry(QRect(550, 220, 51, 21))
        self.label_16 = QLabel(Dialog)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(340, 130, 31, 16))
        self.label_17 = QLabel(Dialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(410, 130, 58, 16))
        self.label_18 = QLabel(Dialog)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(480, 130, 21, 16))
        self.label_19 = QLabel(Dialog)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(550, 130, 71, 16))
        self.lineEdit_58 = QLineEdit(Dialog)
        self.lineEdit_58.setObjectName(u"lineEdit_58")
        self.lineEdit_58.setGeometry(QRect(480, 390, 51, 21))
        self.lineEdit_59 = QLineEdit(Dialog)
        self.lineEdit_59.setObjectName(u"lineEdit_59")
        self.lineEdit_59.setGeometry(QRect(340, 390, 51, 21))
        self.label_20 = QLabel(Dialog)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 390, 31, 16))
        self.lineEdit_60 = QLineEdit(Dialog)
        self.lineEdit_60.setObjectName(u"lineEdit_60")
        self.lineEdit_60.setGeometry(QRect(550, 390, 51, 21))
        self.lineEdit_62 = QLineEdit(Dialog)
        self.lineEdit_62.setObjectName(u"lineEdit_62")
        self.lineEdit_62.setGeometry(QRect(270, 390, 51, 21))
        self.lineEdit_63 = QLineEdit(Dialog)
        self.lineEdit_63.setObjectName(u"lineEdit_63")
        self.lineEdit_63.setGeometry(QRect(410, 390, 51, 21))
        self.lineEdit_64 = QLineEdit(Dialog)
        self.lineEdit_64.setObjectName(u"lineEdit_64")
        self.lineEdit_64.setGeometry(QRect(200, 390, 51, 21))

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"elegir", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"VI", None))

        self.comboBox.setPlaceholderText(QCoreApplication.translate("Dialog", u"Elegir", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("Dialog", u"Elegir", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Dialog", u"asd", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("Dialog", u"4120", None))

        self.comboBox_2.setPlaceholderText(QCoreApplication.translate("Dialog", u"Elegir", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Familia", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Modelo", None))
        self.lineEdit.setText("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"T1", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"T2", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"T3", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"T4", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"T7", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"T5", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"T6", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Trapecios", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"S", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"b_i", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"b_s", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"altura", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"diagonal", None))
        self.lineEdit_10.setText("")
        self.lineEdit_17.setText("")
        self.lineEdit_27.setText("")
        self.lineEdit_30.setText("")
        self.lineEdit_41.setText("")
        self.lineEdit_45.setText("")
        self.lineEdit_54.setText("")
        self.label_16.setText(QCoreApplication.translate("Dialog", u"A", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Cg Sup", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"I", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"I + A*r^2", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"SUM", None))
    # retranslateUi

